name: CI/CD Pipeline
on:
  push:
    branches: [master]

jobs:
  continuos-integration:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Checking out the repo
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.node-version}}
      - name: Cleaning and Installing
        run: npm ci
      - name: Building the application
        run: npm run build --if-present

  continuos-development:
    runs-on: ubuntu-latest
    needs: [continuos-integration]
    if: github.ref == 'refs/heads/master'

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{secrets.AWS_REGION}}
      - name: Create CodeDeploy Deployment
        id: deploy
        run: |
          aws deploy create-deployment \
          --application-name demo_react \
          --deployment-group-name demo_react \
          --deployment-config-name CodeDeployDefault.OneAtATime \
          --github-location repository=${{ github.repository}} \
          --commitId ${{ github.sha}}
